# Generated by Django 4.2 on 2025-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bandera', models.CharField(max_length=100)),
            ],
        ),
    ]
