# Generated by Django 4.2 on 2025-10-23 16:29
import json
from django.db import migrations
import os

def load_initial_data(apps, schema_editor):
    Divisa = apps.get_model('exchange', 'Divisa')
    json_path = os.path.join(os.path.dirname(__file__), '..', 'static', 'exchange', 'data.json')

    with open(json_path, 'r') as f:
        data = json.load(f)

    for divisa_data in data['divisas']:
        bandera_filename = os.path.basename(divisa_data['bandera'])
        Divisa.objects.create(
            nombre=divisa_data['nombre'],
            compra=divisa_data['compra'],
            venta=divisa_data['venta'],
            bandera=bandera_filename
        )

class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]