# Generated by Django 4.2 on 2025-10-24 14:00

from django.db import migrations

def update_bandera_to_country_code(apps, schema_editor):
    Divisa = apps.get_model('exchange', 'Divisa')
    country_code_map = {
        'Dólar': 'us',
        'Euro': 'eu',
        'Real': 'br',
        'Canadá': 'ca',
        'Mexicano': 'mx',
        'Australiano': 'au',
        'Libra': 'gb',
        'Soles': 'pe',
        'Chileno': 'cl',
        'Franco': 'ch',
        'Dominicano': 'do',
        'Yen': 'jp',
        'Yuan': 'cn',
        'Colón': 'cr',
    }
    for divisa in Divisa.objects.all():
        if divisa.nombre in country_code_map:
            divisa.bandera = country_code_map[divisa.nombre]
            divisa.save()

class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20251023_1129'),
    ]

    operations = [
        migrations.RunPython(update_bandera_to_country_code),
    ]